### ISSUE TITLE
Tests are only re-run if I change a *.tests.* file, not if I change implementation files (e.g. server/...)

### ISSUE THREAD

**Issue by perbergland** [meteortesting/meteor-mocha#103]
Meteor 1.10.2, Typescript 3.9.2 using the refapp:meteor-typescript@0.1.0 compiler 

Command line:

`TEST_WATCH=1 TEST_CLIENT=0 MOCHA_TIMEOUT=60000 meteor test --raw-logs --driver-package meteortesting:mocha --inspect=9229 --exclude-archs web.browser,web.browser.legacy`

If I work test-driven so that I have a failing test and then implement the functionality in server/... then Meteor will recompile and restart the server but tests are not re-run.

I need to manually modify the xxx.tests.ts file to force the tests to run again which is a lot of pain (I usually add just a line comment).

How can I change the behaviour so that tests are run again whenever Meteor restarts?

**Comment by SimonSimCity** [comment]
Well ... the tests should automatically restart every time Meteor restarts. If meteor doesn't restart, it's the responsibility of the utility file watching for changes in the files.

Either way, this package is only responsible of initialising all tests included in the files Meteor loads (https://guide.meteor.com/testing.html#test-modes) and runs them.

Deciding when to restart Meteor (and thereby rerun the tests) or which files to load is not the responsibility of this package, but of Meteor. It might even be the responsibility of the typescript package, which doesn't seem to tell Meteor that the file containing the implementation actually is required for the test-file as well.

Btw ... do you define a testing-module or a main-module in your `package.json` file?
```
  "meteor": {
     "mainModule": {
       "client": "client/main.js",
       "server": "server/main.js"
     },
     "testModule": "tests/main.js"
   }

**Comment by perbergland** [comment]
Oh OK so for Javascript this works properly. Good to know.

Do you know if Meteor builds a dependency graph to only run tests that are affected for Javascript or does it always re-run all tests for Javascript?

As for main-module, no I haven’t added that section. What does it change?

**Comment by SimonSimCity** [comment]
I just checked it - it works on fine on files included in one of my `*.test.js` files, but if they're not included, the system won't watch it. I have a `mainModule` but not a `testModule` defined in my `package.json` file.

The section `mainModule` and `testModule` in the `package.json` changes the way files are included, which might affect the way they are monitored also. All this can have its share to this problem you're facing. It could even be that the package `refapp:meteor-typescript@0.1.0` doens't tell Meteor which files to watch and which not.

Closing, because this is not related to this package, but to https://github.com/meteor/meteor and therefore yields to all test-runners - not only for this one.
