### ISSUE TITLE
Colooooooooooors

### ISSUE THREAD

**Issue by workflow** [meteortesting/meteor-mocha#30]
Why hello there and thank you for packaging mocha for Meteor in this awesome way.

Very important: Seems like the colors in CLI reporter are getting lost somewhere in translation.
This is how it could look:

![image](https://cloud.githubusercontent.com/assets/1276854/25829104/80ce6ea8-3454-11e7-8f31-80080c0e830b.png)

I mean - how cool would that be?

Any chance it's easy to get them back?

**Comment by aldeed** [comment]
I remember playing with trying to keep the colors, but didn't get it figured out. In theory, server colors should be OK if writing to stdout instead of using `console.log`, but there are several layers getting client errors over to the server console, and colors are stripped out during that process. It will also vary by which browser driver is used. It would be great if someone can figure it out, but it's not straightforward.

**Comment by workflow** [comment]
After a lot of playing around - as you said, it's quite tangled and not too well documented on the mocha side - it turns out the solution is actually very simple :)

https://github.com/meteortesting/meteor-mocha/pull/41

Works for me on both client and server.

**Comment by aldeed** [comment]
Released in 0.5.0
