### ISSUE TITLE
XUnit also for client side tests

### ISSUE THREAD

**Issue by uglywizkid** [meteortesting/meteor-mocha#40]
Unfortunately CLIENT_TEST_REPORTER=xunit does not work. Only server side test are exported into xunit xml file.

**Comment by singhsoldier13** [comment]
+1

**Comment by thebarty** [comment]
Yeah - plus one. Actually I am also seeing a `Load the app in a browser to run client tests, or set the TEST_BROWSER_DRIVER environment variable. See https://github.com/meteortesting/meteor-mocha/blob/master/README.md#run-app-tests ` error when calling via `SERVER_TEST_REPORTER=xunit XUNIT_FILE=$PWD/unit-integrationa-results.xml meteor test --once --driver-package meteortesting:mocha`

**Comment by SimonSimCity** [comment]
This should be fixed in version `1.1.0`. When you now set the `MOCHA_REPORTER` to `xunit` (or separately via `SERVER_TEST_REPORTER` and `CLIENT_TEST_REPORTER`) you'll see, that the output of both test-environments will be in the `xunit` format.

You then should also set `SERVER_MOCHA_OUTPUT` (which replaces `XUNIT_FILE`) and `CLIENT_MOCHA_OUTPUT` to the path you want to see the test reports in.

In case it doesn't work, please make sure that this and the package `meteortesting:browser-tests` are installed in the latest version and that you run the tests using a headless browser as described in https://github.com/meteortesting/meteor-browser-tests#dependencies (the documentation on this package regarding headless browsers is a bit outdated 😉 - that's why I linked directly to the package providing this feature).

**Comment by Floriferous** [comment]
Client-side tests don't seem to report properly for me. I can see the file on CircleCI being generated, and its content appears to be ok, but circleCI complains:


<img width="1559" alt="screenshot 2019-02-04 at 11 03 42" src="https://user-images.githubusercontent.com/10428082/52201733-a87f3a00-286c-11e9-81d0-c03697f20fa8.png">

<img width="1191" alt="screenshot 2019-02-04 at 11 03 33" src="https://user-images.githubusercontent.com/10428082/52201732-a87f3a00-286c-11e9-9def-8700ca80e3b9.png">

Would you have an idea what could be wrong with the file?

**Comment by Floriferous** [comment]
Could we maybe clean up the xml file at the end? It's a bit hacky, but removing any "non-xml" content from the file could already be a coarse filter.

I think it might be safe to say very few people would ever console.log xml-valid content.

**Comment by SimonSimCity** [comment]
Could do that ... I'd prefer a separate issue for this, since the main purpose of this ticket is solved and this (to me) is a separate ticket.

If we would cut out some of the data returned by calling `console.log()` I'd at least put it out on `stdout` - not simply ignore it, but this is up for a discussion which I'd take in the new ticket. If you have time, I'd also welcome a PR. Otherwise you'd have to wait until someone else (e.g. me) finds time to pick it up.
