### ISSUE TITLE
Update or incorporate practicalmeteor:mocha-core 

### ISSUE THREAD

**Issue by lpgeiger** [meteortesting/meteor-mocha#8]
practicalmeteor:mocha-core hasn't been maintained since June 2016, It may be worth preventively updating the packages there.

It's not a big package, and I'm not sure if the separation of concerns is critical in this case. It may be worth incorporating it here. For example: Some features such as grep, or custom reporters would need patching to the practicalmeteor:mocha-core code.

**Comment by aldeed** [comment]
I collaborated with them on that package, and we need to use the same core package as practicalmeteor:mocha in order to avoid dependency issues when your app uses both drivers. I'd like to discuss with the practicalmeteor guys possible moving all of these test packages into a "testing" org or something like that so that we can maintain them all together.

One thing we could look at doing is to make `mocha` NPM package a peer dependency, in which case the mocha-core pkg will likely never need any updating unless the mocha API changes.

**Comment by SimonSimCity** [comment]
We've created a fork which we now will support on our own: https://github.com/meteortesting/meteor-mocha-core
