### ISSUE TITLE
Only run tests whose path contains X

### ISSUE THREAD

**Issue by Floriferous** [meteortesting/meteor-mocha#92]
`MOCHA_GREP` is useful if you write your test suites and names a certain way, but I'd like to be able to exclude/include a certain folder of tests.

Is there any way to achieve this?

For example: 
`MOCHA_GREP_FILES="**/myFolder/**" meteor test --driver-package meteortesting:mocha`

**Comment by SimonSimCity** [comment]
Since Meteor does the import of test files automatically, I don't see a way this plugin could do anything about it.

The only way that comes into my mind is available since Meteor `1.7` https://github.com/meteor/meteor/blob/devel/History.md#v17-2018-05-28 where they introduced the `meteor.mainModule` block into the `package.json` file. Alongside with this addition, they also added `meteor. testModule` which, if defined, is the only file loaded for testing. See https://github.com/meteor/meteor/pull/9714 for further details on integration.
