### ISSUE TITLE
Feature Request: How to really run server tests in parallel?

### ISSUE THREAD

**Issue by ldepaiva** [meteortesting/meteor-mocha#93]
Hi There,

I am wondering if is there any env flag that I can pass to really run all the server tests in parallel? I looked at the code and the `TEST_PARALLEL=1` will run client and server tests simultaneously but it will run each one serially.

All my server tests are stateless and I would like to really run them in parallel. I found this package [mocha-parallel-tests](https://github.com/mocha-parallel/mocha-parallel-tests) which I think is exactly what I want and we could integrate that with this package to replace the current mocha instance upon some env flag. I could make the tests run much faster.

What do you think? Would that be a nice feature to have in?

**Comment by SimonSimCity** [comment]
I think this would at first require a change in Meteor.

If anyone is keen enough to push into this, PRs are very welcome, and I'd assist him as much as I can.

**Comment by SimonSimCity** [comment]
Since we introduced mocha configuration files (see the docs of the package meteor-mocha-core: https://github.com/meteortesting/meteor-mocha-core#mocha-configuration-with-mocharc-file) in version 7.2.0 of the pacakge, you can set the option `parallel`, as described in the mocha-specs: https://mochajs.org/api/mocha.

Setting this will run both client and server tests in parallel, according to how mocha would do it. Please be aware that both the client- and the server-tests will still be ran sequentially (first all server, than all client tests) unless you add `TEST_PARALLEL=1` as well.

Just to put this out right now: You also need a reporter which supports this. The default reporter, I guess, would create a mess if I'd try to run my tests in parallel. The `tap` reporter is one which seems suitable - but I might be missguided here.
